# Generated by Django 4.1.2 on 2022-11-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Jobs", new_name="Job",),
        migrations.RenameField(
            model_name="candidate", old_name="years", new_name="yoe",
        ),
        migrations.AlterField(
            model_name="candidate", name="bio", field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="recruiter", name="zip", field=models.IntegerField(),
        ),
    ]
