# Generated by Django 4.1.3 on 2022-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_jobs_job_rename_years_candidate_yoe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
