# Generated by Django 4.1.3 on 2022-11-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_job_status_job_active_job_author_job_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='numCandidates',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
