# Generated by Django 4.1.3 on 2022-11-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_job_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='coverImage',
            field=models.ImageField(default='app/static/images/errorImage.jpg', upload_to='app/static/images'),
        ),
    ]
