# Generated by Django 4.1.3 on 2022-11-29 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_job_coverimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='coverImage',
        ),
    ]
