# Generated by Django 4.1.3 on 2022-11-30 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_job_coverimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='inactive',
        ),
    ]
