# Generated by Django 4.1.3 on 2022-12-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_applications_offers_candidate_disinterested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='test',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.TextField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='github',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
