# Generated by Django 4.1.3 on 2022-12-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_candidate_test_alter_candidate_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='test',
        ),
    ]
