# Generated by Django 4.1.2 on 2022-12-07 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_candidate_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profilePicture',
            field=models.ImageField(default='../../static/images/errorImage.jpg', upload_to='app/static/images'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='zip',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='zip',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
    ]
